# image will be published to ghcr.io/<user>/<name>
name: startingpoint-wayfire
# description will be included in the image's metadata
description: My personal wayfire-based image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be 
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README
      - lib: /lib

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/alebastr/sway-extras/repo/fedora-%OS_VERSION%/alebastr-sway-extras-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/charlieqle/rpmspec/repo/fedora-%OS_VERSION%/charlieqle-rpmspec-fedora-%OS_VERSION%.repo
      - https://terra.fyralabs.com/terra.repo
    install:
      # - micro
      # - starship
      - adw-gtk3-theme
      - adwaita-icon-theme
      - bluez
      - bluez-libs
      - brightnessctl
      - btop
      - corectrl
      - fprintd
      - fprintd-pam
      - gjs
      - gnome-bluetooth-libs
      - gnome-keyring
      - gnome-keyring-pam
      - gnome-online-accounts
      - grim
      - gtk3
      - gtk4
      - gtk-layer-shell
      - gtk4-layer-shell
      - gvfs
      - gvfs-fuse
      - gvfs-smb
      - gvfs-mtp
      - libadwaita
      - libatomic
      - libratbag-ratbagd
      - lm_sensors
      - nautilus
      - nautilus-extensions
      - nautilus-python
      - ncdu
      - nm-connection-editor
      - nvtop
      - nwg-launchers
      - openresolv
      - openvpn
      - playerctl
      - polkit-gnome
      - pulseaudio-utils
      - qt5-qtwayland
      - qt6-qtwayland
      - rofi-wayland
      - slurp
      - starship
      - swayidle
      - swaylock
      - swww
      - udiskie
      - wayfire-git
      - wayfire-plugins-extra-git
      - wayland-logout
      - wayvnc
      - wf-shell
      - wl-clipboard
      - wlr-randr
      - wofi
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xrandr
      - yubikey-manager-qt
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
